spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/TEST_CRUD
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
